ALTER TABLE tbl_tasks
DROP COLUMN status;

CREATE TYPE task_status AS ENUM ('COMPLETED', 'INPROGRESS', 'UNCOMPLETED');
ALTER TABLE tbl_tasks ADD COLUMN status task_status NOT NULL DEFAULT 'UNCOMPLETED';