ALTER TABLE tbl_units
    ADD COLUMN created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tbl_units
    ADD COLUMN updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE tbl_common_problems
    ADD COLUMN created_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE tbl_common_problems
    ADD COLUMN updated_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP;